use std::env;
use std::fs;
use std::path::PathBuf;
use std::process::Command;

use anyhow::{anyhow, Context, Result};

fn main() {
    if let Err(err) = run() {
        eprintln!("xtask error: {err:#}");
        std::process::exit(1);
    }
}

fn run() -> Result<()> {
    let mut args = env::args().skip(1);
    let Some(cmd) = args.next() else {
        return Err(anyhow!("usage: cargo xtask <ci-fast|ci-full|smoke|scenario-index|mutants|docs-check|release-check>"));
    };

    match cmd.as_str() {
        "ci-fast" => {
            run_cmd("cargo", &["fmt", "--all", "--check"])?;
            run_cmd(
                "cargo",
                &["clippy", "--workspace", "--all-targets", "--all-features", "--", "-D", "warnings"],
            )?;
            Ok(())
        }
        "ci-full" => {
            run_cmd("cargo", &["xtask", "ci-fast"])?;
            run_cmd("cargo", &["test", "--workspace"])?;
            Ok(())
        }
        "smoke" => {
            run_cmd("cargo", &["run", "-p", "repropack-cli", "--", "--help"])?;
            run_cmd("cargo", &["run", "-p", "repropack-cli", "--", "emit", "github-actions"])?;
            Ok(())
        }
        "scenario-index" => {
            let out = scenario_index();
            let path = PathBuf::from("docs/scenario_index.md");
            fs::write(&path, out).with_context(|| format!("writing {}", path.display()))?;
            println!("{}", path.display());
            Ok(())
        }
        "mutants" => {
            run_cmd("cargo", &["mutants", "--workspace"])?;
            Ok(())
        }
        "docs-check" => {
            for file in [
                "README.md",
                "PACKET-SPEC.md",
                "REPLAY.md",
                "SECURITY.md",
                "TESTING.md",
                "AGENTS.md",
                "docs/architecture.md",
                "docs/scenario_index.md",
            ] {
                if !PathBuf::from(file).exists() {
                    return Err(anyhow!("required doc is missing: {file}"));
                }
            }
            println!("docs present");
            Ok(())
        }
        "release-check" => {
            run_cmd("cargo", &["xtask", "ci-full"])?;
            run_cmd("cargo", &["xtask", "docs-check"])?;
            run_cmd("cargo", &["run", "-p", "repropack-cli", "--", "emit", "github-actions"])?;
            Ok(())
        }
        other => Err(anyhow!("unknown xtask command: {other}")),
    }
}

fn scenario_index() -> &'static str {
    r#"# Scenario atlas

This file is generated by `cargo xtask scenario-index`.

| Scenario | Problem | Crates | Artifact | Notes |
|---|---|---|---|---|
| capture clean commit failure | preserve a red predicate with commit state | `capture`, `git`, `pack`, `render` | `manifest.json`, `summary.md` | basic CI path |
| capture dirty worktree failure | preserve local deltas honestly | `capture`, `git` | `worktree.patch` | tracked changes only unless explicitly included |
| inspect packet without replay | answer what ran and what happened | `pack`, `render`, `cli` | `summary.md`, JSON | offline operator path |
| replay from bundle | reconstruct repo and rerun | `replay`, `git` | `receipt.json` | host replay only |
| blocked replay policy | avoid unsafe reruns | `replay`, `cli` | `receipt.json` | `confirm` needs `--force`; `disabled` blocks |
| redacted environment capture | preserve safety while keeping evidence | `capture`, `render` | omissions + summary | redactions are explicit |
| missing glob matches | make incomplete packets honest | `capture` | omissions | no hidden no-ops |

The atlas should grow alongside behavior.
"#
}

fn run_cmd(program: &str, args: &[&str]) -> Result<()> {
    let status = Command::new(program)
        .args(args)
        .status()
        .with_context(|| format!("running {program} {:?}", args))?;

    if status.success() {
        Ok(())
    } else {
        Err(anyhow!("{program} {:?} exited with status {status}", args))
    }
}
