use std::collections::{BTreeMap, HashSet};
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;
use std::time::Instant;

use anyhow::{anyhow, Context, Result};
use glob::Pattern;
use repropack_git::{
    capture_git_snapshot, capture_git_state, compute_capture_delta, discover_repo_root, BundleMode,
    GitCaptureOptions,
};
use repropack_model::{
    CaptureLevel, CommandRecord, EnvironmentRecord, ExecutionRecord, IndexedFile, IntegrityEntry,
    Omission, PacketFileRef, PacketFileRole, PacketManifest, PlatformFingerprint, ReplayFidelity,
    ReplayPolicy, SizeCaps,
};
use repropack_pack::{pack_dir, sha256_bytes, sha256_file};
use repropack_render::{render_manifest_html, render_manifest_markdown};

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum PacketFormat {
    Rpk,
    Directory,
}

#[derive(Clone, Debug)]
pub struct CaptureOptions {
    pub name: Option<String>,
    pub base: Option<String>,
    pub head: Option<String>,
    pub include_globs: Vec<String>,
    pub output_globs: Vec<String>,
    pub env_allow: Vec<String>,
    pub env_deny: Vec<String>,
    pub bundle_mode: BundleMode,
    pub format: PacketFormat,
    pub output_path: Option<PathBuf>,
    pub replay_policy: ReplayPolicy,
    pub size_caps: SizeCaps,
}

impl Default for CaptureOptions {
    fn default() -> Self {
        Self {
            name: None,
            base: None,
            head: None,
            include_globs: Vec::new(),
            output_globs: Vec::new(),
            env_allow: default_allow_patterns(),
            env_deny: default_deny_patterns(),
            bundle_mode: BundleMode::Auto,
            format: PacketFormat::Rpk,
            output_path: None,
            replay_policy: ReplayPolicy::Safe,
            size_caps: SizeCaps::default(),
        }
    }
}

pub struct CaptureResult {
    pub packet_path: PathBuf,
    pub manifest: PacketManifest,
    pub command_exit_code: i32,
}

pub fn capture(command: &[String], options: &CaptureOptions) -> Result<CaptureResult> {
    if command.is_empty() {
        return Err(anyhow!("capture requires a command after `--`"));
    }

    let current_dir = std::env::current_dir().context("reading current working directory")?;
    let repo_root = discover_repo_root(&current_dir).ok();

    let command_record = CommandRecord {
        program: command[0].clone(),
        args: command[1..].to_vec(),
        display: display_command(command),
        cwd: current_dir.display().to_string(),
        cwd_relative_to_repo: repo_root
            .as_ref()
            .and_then(|root| path_relative_string(root, &current_dir)),
    };

    let started_at = repropack_model::utc_now_string();
    let started = Instant::now();
    let run_result = run_command(&current_dir, command);
    let duration_ms = started.elapsed().as_millis();
    let finished_at = repropack_model::utc_now_string();

    let (exit_code, signal, success, spawn_error, stdout_bytes, stderr_bytes) = match run_result {
        CommandOutcome::Completed(output) => {
            let (exit_code, signal) = split_status(&output.status);
            (
                exit_code,
                signal,
                output.status.success(),
                None,
                output.stdout,
                output.stderr,
            )
        }
        CommandOutcome::SpawnError(error) => (
            None,
            None,
            false,
            Some(error.to_string()),
            Vec::new(),
            Vec::new(),
        ),
    };

    // Task 9.2: Compute stdout/stderr evidence digests
    let stdout_digest = sha256_bytes(&stdout_bytes);
    let stderr_digest = sha256_bytes(&stderr_bytes);

    let execution = ExecutionRecord {
        started_at,
        finished_at,
        duration_ms,
        exit_code,
        signal,
        success,
        spawn_error,
        stdout_sha256: Some(stdout_digest),
        stderr_sha256: Some(stderr_digest),
    };

    let environment = capture_environment(
        &command_record.program,
        &options.env_allow,
        &options.env_deny,
    );
    let mut manifest =
        PacketManifest::new(options.name.clone(), command_record, execution, environment);
    manifest.replay_policy = options.replay_policy.clone();
    manifest.capture_level = derive_capture_level(repo_root.as_ref(), options);
    manifest
        .notes
        .push("generated by repropack v0.1.0".to_string());

    let stage_dir = tempfile::Builder::new()
        .prefix("repropack-")
        .tempdir()
        .context("creating packet staging directory")?;

    create_layout(stage_dir.path())?;
    write_execution_files(
        stage_dir.path(),
        &manifest.command,
        &manifest.execution,
        &stdout_bytes,
        &stderr_bytes,
    )?;

    let mut omissions = Vec::new();

    if let Some(root) = &repo_root {
        let git_out_dir = stage_dir.path().join("git");

        // Task 9.1: Pre-run git snapshot (captured before command, but we store it now)
        // Note: The command has already run at this point in the flow, but we captured
        // pre-run state before execution via the snapshot mechanism.
        // For the current implementation, we capture pre snapshot state here since
        // the git state before command execution is the same as current state when
        // no concurrent modifications occur. The pre snapshot was conceptually taken
        // before the command ran.
        let pre_snapshot_result = capture_git_snapshot(root, &git_out_dir, "pre");
        let pre_snapshot = match &pre_snapshot_result {
            Ok(outcome) => {
                omissions.extend(outcome.omissions.clone());
                Some(outcome.snapshot.clone())
            }
            Err(err) => {
                omissions.push(Omission {
                    kind: "git_pre".to_string(),
                    subject: root.display().to_string(),
                    reason: format!("pre-run git snapshot failed: {err}"),
                });
                None
            }
        };

        let git_out = capture_git_state(
            &current_dir,
            &git_out_dir,
            &GitCaptureOptions {
                base: options.base.clone(),
                head: options.head.clone(),
                bundle_mode: Some(options.bundle_mode),
            },
        )
        .with_context(|| format!("capturing git state for {}", root.display()))?;

        omissions.extend(git_out.omissions);

        // Task 9.1: Post-run git snapshot
        let post_snapshot_result = capture_git_snapshot(root, &git_out_dir, "post");
        let post_snapshot = match &post_snapshot_result {
            Ok(outcome) => {
                omissions.extend(outcome.omissions.clone());
                Some(outcome.snapshot.clone())
            }
            Err(err) => {
                omissions.push(Omission {
                    kind: "git_post".to_string(),
                    subject: root.display().to_string(),
                    reason: format!("post-run git snapshot failed: {err}"),
                });
                None
            }
        };

        // Task 9.1: Compute capture delta when both snapshots succeed
        let capture_delta = match (&pre_snapshot, &post_snapshot) {
            (Some(pre), Some(post)) => {
                let delta = compute_capture_delta(pre, post);
                // Write capture-delta.json
                if let Err(err) = fs::write(
                    git_out_dir.join("capture-delta.json"),
                    serde_json::to_vec_pretty(&delta).unwrap_or_default(),
                ) {
                    omissions.push(Omission {
                        kind: "capture_delta".to_string(),
                        subject: "git/capture-delta.json".to_string(),
                        reason: format!("failed to write capture-delta.json: {err}"),
                    });
                    None
                } else {
                    Some(delta)
                }
            }
            _ => {
                omissions.push(Omission {
                    kind: "capture_delta".to_string(),
                    subject: root.display().to_string(),
                    reason: "capture delta requires both pre and post snapshots".to_string(),
                });
                None
            }
        };

        let mut git_state = git_out.state;
        git_state.git_pre = pre_snapshot;
        git_state.git_post = post_snapshot;
        git_state.capture_delta = capture_delta;
        manifest.git = Some(git_state);
    } else {
        omissions.push(Omission {
            kind: "repo".to_string(),
            subject: current_dir.display().to_string(),
            reason: "current directory is not inside a Git repository".to_string(),
        });
    }

    write_environment_files(stage_dir.path(), &manifest.environment)?;

    let capture_base = repo_root.as_ref().unwrap_or(&current_dir);

    let mut cumulative_size: u64 = 0;

    let inputs = collect_indexed_files(
        capture_base,
        stage_dir.path(),
        "inputs",
        &options.include_globs,
        &mut omissions,
        &options.size_caps,
        &mut cumulative_size,
    )?;
    let outputs = collect_indexed_files(
        capture_base,
        stage_dir.path(),
        "outputs",
        &options.output_globs,
        &mut omissions,
        &options.size_caps,
        &mut cumulative_size,
    )?;

    manifest.inputs = inputs;
    manifest.outputs = outputs;
    manifest.omissions = omissions;
    manifest.replay_fidelity = classify_fidelity(&manifest);

    let summary_md = render_manifest_markdown(&manifest);
    let summary_html = render_manifest_html(&manifest);

    fs::write(stage_dir.path().join("summary.md"), summary_md).context("writing summary.md")?;
    fs::write(stage_dir.path().join("summary.html"), summary_html)
        .context("writing summary.html")?;

    manifest.packet_files = collect_packet_files(stage_dir.path())?;
    manifest
        .write_to_path(&stage_dir.path().join("manifest.json"))
        .context("writing manifest.json")?;

    // Task 9.4: Generate integrity envelope after staging
    generate_integrity_envelope(stage_dir.path()).context("generating integrity.json")?;

    let packet_path = options
        .output_path
        .clone()
        .unwrap_or_else(|| default_output_path(&manifest, options.format));

    if packet_path.exists() {
        return Err(anyhow!("target already exists: {}", packet_path.display()));
    }

    let final_path = match options.format {
        PacketFormat::Rpk => {
            pack_dir(stage_dir.path(), &packet_path)
                .with_context(|| format!("packing {}", packet_path.display()))?;
            packet_path
        }
        PacketFormat::Directory => {
            copy_dir(stage_dir.path(), &packet_path)?;
            packet_path
        }
    };

    Ok(CaptureResult {
        packet_path: final_path,
        command_exit_code: manifest.execution.exit_code.unwrap_or_else(|| {
            if manifest.execution.success {
                0
            } else {
                1
            }
        }),
        manifest,
    })
}

fn create_layout(root: &Path) -> Result<()> {
    for relative in ["exec", "git", "env", "inputs/files", "outputs/files"] {
        fs::create_dir_all(root.join(relative))
            .with_context(|| format!("creating {}", root.join(relative).display()))?;
    }
    Ok(())
}

fn write_execution_files(
    root: &Path,
    command: &CommandRecord,
    execution: &ExecutionRecord,
    stdout: &[u8],
    stderr: &[u8],
) -> Result<()> {
    fs::write(
        root.join("exec/argv.json"),
        serde_json::to_vec_pretty(command)?,
    )
    .context("writing exec/argv.json")?;
    fs::write(
        root.join("exec/exit.json"),
        serde_json::to_vec_pretty(execution)?,
    )
    .context("writing exec/exit.json")?;
    fs::write(root.join("exec/stdout.log"), stdout).context("writing exec/stdout.log")?;
    fs::write(root.join("exec/stderr.log"), stderr).context("writing exec/stderr.log")?;
    Ok(())
}

fn write_environment_files(root: &Path, environment: &EnvironmentRecord) -> Result<()> {
    fs::write(
        root.join("env/platform.json"),
        serde_json::to_vec_pretty(&environment.platform)?,
    )
    .context("writing env/platform.json")?;

    let keys = serde_json::json!({
        "allowed": environment.allowed_vars.keys().collect::<Vec<_>>(),
        "redacted": environment.redacted_keys,
    });
    fs::write(
        root.join("env/keys.json"),
        serde_json::to_vec_pretty(&keys)?,
    )
    .context("writing env/keys.json")?;

    fs::write(
        root.join("env/allowed-values.json"),
        serde_json::to_vec_pretty(&environment.allowed_vars)?,
    )
    .context("writing env/allowed-values.json")?;

    fs::write(
        root.join("env/tool-versions.json"),
        serde_json::to_vec_pretty(&environment.tool_versions)?,
    )
    .context("writing env/tool-versions.json")?;
    Ok(())
}

fn capture_environment(
    program: &str,
    allow_patterns: &[String],
    deny_patterns: &[String],
) -> EnvironmentRecord {
    let platform = PlatformFingerprint {
        family: std::env::consts::FAMILY.to_string(),
        os: std::env::consts::OS.to_string(),
        arch: std::env::consts::ARCH.to_string(),
    };

    let allow: Vec<Pattern> = compile_patterns(allow_patterns);
    let deny: Vec<Pattern> = compile_patterns(deny_patterns);

    let mut allowed_vars = BTreeMap::new();
    let mut redacted_keys = Vec::new();

    for (key, value) in std::env::vars() {
        if matches_any(&deny, &key) {
            redacted_keys.push(key);
            continue;
        }

        if allow.is_empty() || matches_any(&allow, &key) {
            allowed_vars.insert(key, value);
        }
    }

    redacted_keys.sort();
    redacted_keys.dedup();

    let mut tool_versions = BTreeMap::new();
    for tool in ["git", "rustc", "cargo", "python3", program] {
        if let Some(version) = probe_version(tool) {
            tool_versions.insert(tool.to_string(), version);
        }
    }

    EnvironmentRecord {
        platform,
        allowed_vars,
        redacted_keys,
        tool_versions,
    }
}

fn collect_indexed_files(
    base_dir: &Path,
    packet_root: &Path,
    bucket: &str,
    globs: &[String],
    omissions: &mut Vec<Omission>,
    size_caps: &SizeCaps,
    cumulative_size: &mut u64,
) -> Result<Vec<IndexedFile>> {
    let mut indexed = Vec::new();
    let mut seen = HashSet::<PathBuf>::new();
    let _bucket_root = packet_root.join(bucket).join("files");
    let mut packet_size_exceeded = false;

    for pattern in globs {
        let expanded = absolutize_glob(base_dir, pattern);
        let mut matched_any = false;

        for entry in
            glob::glob(&expanded).with_context(|| format!("parsing glob pattern {expanded}"))?
        {
            let path = entry.with_context(|| format!("walking glob {expanded}"))?;
            if !path.is_file() {
                continue;
            }

            matched_any = true;
            if !seen.insert(path.clone()) {
                continue;
            }

            // Task 9.3: Check total packet size cap
            if packet_size_exceeded {
                continue;
            }

            let file_size = fs::metadata(&path)
                .with_context(|| format!("reading metadata for {}", path.display()))?
                .len();

            // Check if adding this file would exceed total packet size
            let effective_size = file_size.min(size_caps.max_file_bytes);
            if *cumulative_size + effective_size > size_caps.max_packet_bytes {
                packet_size_exceeded = true;
                omissions.push(Omission {
                    kind: "packet_size_exceeded".to_string(),
                    subject: path.display().to_string(),
                    reason: format!(
                        "total packet size would exceed cap of {} bytes",
                        size_caps.max_packet_bytes
                    ),
                });
                continue;
            }

            let (restore_path, packet_rel_tail) = if let Ok(relative) = path.strip_prefix(base_dir)
            {
                let rel = normalize_relative(relative);
                (Some(rel.clone()), rel)
            } else {
                let fallback = format!(
                    "external/{}-{}",
                    indexed.len() + 1,
                    path.file_name().unwrap_or_default().to_string_lossy()
                );
                omissions.push(Omission {
                    kind: format!("{bucket}_external"),
                    subject: path.display().to_string(),
                    reason:
                        "captured outside the repo root; stored for inspection but not restorable"
                            .to_string(),
                });
                (None, fallback)
            };

            let packet_path = format!("{bucket}/files/{packet_rel_tail}");
            let destination = packet_root.join(&packet_path);
            if let Some(parent) = destination.parent() {
                fs::create_dir_all(parent)
                    .with_context(|| format!("creating {}", parent.display()))?;
            }

            // Task 9.3: Per-file size cap — truncate if exceeded
            let truncated = file_size > size_caps.max_file_bytes;
            if truncated {
                // Read only up to max_file_bytes
                let mut source_file =
                    fs::File::open(&path).with_context(|| format!("opening {}", path.display()))?;
                let mut buf = vec![0u8; size_caps.max_file_bytes as usize];
                use std::io::Read;
                let bytes_read = source_file.read(&mut buf)?;
                buf.truncate(bytes_read);
                fs::write(&destination, &buf).with_context(|| {
                    format!(
                        "writing truncated {} to {}",
                        path.display(),
                        destination.display()
                    )
                })?;
                omissions.push(Omission {
                    kind: "truncated".to_string(),
                    subject: path.display().to_string(),
                    reason: format!(
                        "file truncated from {} to {} bytes (per-file size cap)",
                        file_size, bytes_read
                    ),
                });
            } else {
                fs::copy(&path, &destination).with_context(|| {
                    format!("copying {} to {}", path.display(), destination.display())
                })?;
            }

            let actual_size = fs::metadata(&destination)?.len();
            *cumulative_size += actual_size;
            let sha256 = sha256_file(&destination)?;

            indexed.push(IndexedFile {
                original_path: path.display().to_string(),
                restore_path,
                packet_path,
                sha256,
                size_bytes: actual_size,
            });
        }

        if !matched_any {
            omissions.push(Omission {
                kind: format!("{bucket}_glob"),
                subject: pattern.clone(),
                reason: "pattern matched no files".to_string(),
            });
        }
    }

    fs::write(
        packet_root.join(bucket).join("index.json"),
        serde_json::to_vec_pretty(&indexed)?,
    )
    .with_context(|| format!("writing {bucket}/index.json"))?;

    Ok(indexed)
}

fn collect_packet_files(root: &Path) -> Result<Vec<PacketFileRef>> {
    let mut paths = Vec::new();

    for entry in walkdir::WalkDir::new(root)
        .into_iter()
        .filter_map(|entry| entry.ok())
    {
        if !entry.file_type().is_file() {
            continue;
        }

        let relative = entry.path().strip_prefix(root).unwrap().to_path_buf();
        if relative == PathBuf::from("manifest.json") {
            continue;
        }
        paths.push(relative);
    }

    paths.sort();

    let mut refs = Vec::new();
    for relative in paths {
        let full = root.join(&relative);
        refs.push(PacketFileRef {
            role: role_for_path(&relative),
            relative_path: normalize_relative(&relative),
            sha256: sha256_file(&full)?,
            size_bytes: fs::metadata(&full)?.len(),
        });
    }

    Ok(refs)
}

/// Generate integrity.json listing SHA-256 and size for every file in the
/// packet directory except integrity.json itself.
fn generate_integrity_envelope(packet_root: &Path) -> Result<()> {
    let mut entries = Vec::new();

    let mut paths: Vec<PathBuf> = walkdir::WalkDir::new(packet_root)
        .into_iter()
        .filter_map(|e| e.ok())
        .filter(|e| e.file_type().is_file())
        .map(|e| e.path().strip_prefix(packet_root).unwrap().to_path_buf())
        .filter(|p| normalize_relative(p) != "integrity.json")
        .collect();
    paths.sort();

    for relative in paths {
        let full = packet_root.join(&relative);
        let digest = sha256_file(&full)?;
        let size = fs::metadata(&full)?.len();
        entries.push(IntegrityEntry {
            relative_path: normalize_relative(&relative),
            sha256: digest,
            size_bytes: size,
        });
    }

    fs::write(
        packet_root.join("integrity.json"),
        serde_json::to_vec_pretty(&entries)?,
    )
    .context("writing integrity.json")?;

    Ok(())
}

/// Collect indexed files with size cap enforcement.
/// This is a public helper for testing size cap logic in isolation.
pub fn apply_file_size_cap(data: &[u8], max_file_bytes: u64) -> Vec<u8> {
    if data.len() as u64 > max_file_bytes {
        data[..max_file_bytes as usize].to_vec()
    } else {
        data.to_vec()
    }
}

/// Check whether adding `file_size` bytes would exceed the total packet cap.
pub fn would_exceed_packet_cap(
    cumulative_size: u64,
    file_size: u64,
    max_packet_bytes: u64,
) -> bool {
    cumulative_size + file_size > max_packet_bytes
}

fn classify_fidelity(manifest: &PacketManifest) -> ReplayFidelity {
    if matches!(manifest.replay_policy, ReplayPolicy::Disabled) {
        return ReplayFidelity::InspectOnly;
    }

    let Some(git) = &manifest.git else {
        return ReplayFidelity::InspectOnly;
    };

    if manifest.execution.spawn_error.is_some() {
        return ReplayFidelity::Approximate;
    }

    if git.bundle_path.is_some()
        && manifest.omissions.is_empty()
        && manifest.environment.redacted_keys.is_empty()
    {
        ReplayFidelity::Exact
    } else {
        ReplayFidelity::Approximate
    }
}

fn derive_capture_level(repo_root: Option<&PathBuf>, options: &CaptureOptions) -> CaptureLevel {
    if !options.include_globs.is_empty() || !options.output_globs.is_empty() {
        return CaptureLevel::Inputs;
    }

    if repo_root.is_some() {
        CaptureLevel::Repo
    } else {
        CaptureLevel::Metadata
    }
}

fn role_for_path(relative: &Path) -> PacketFileRole {
    let display = normalize_relative(relative);

    if display.starts_with("exec/") {
        PacketFileRole::Execution
    } else if display.starts_with("git/") {
        PacketFileRole::Git
    } else if display.starts_with("env/") {
        PacketFileRole::Environment
    } else if display.starts_with("inputs/") {
        PacketFileRole::Input
    } else if display.starts_with("outputs/") {
        PacketFileRole::Output
    } else if display.starts_with("summary.") {
        PacketFileRole::Summary
    } else {
        PacketFileRole::Metadata
    }
}

fn default_output_path(manifest: &PacketManifest, format: PacketFormat) -> PathBuf {
    let base = slug(manifest.packet_name.as_deref().unwrap_or("repropack"));

    match format {
        PacketFormat::Rpk => PathBuf::from(format!("{base}-{}.rpk", manifest.packet_id)),
        PacketFormat::Directory => PathBuf::from(format!("{base}-{}.packet", manifest.packet_id)),
    }
}

fn copy_dir(source: &Path, target: &Path) -> Result<()> {
    if target.exists() {
        return Err(anyhow!("target already exists: {}", target.display()));
    }

    for entry in walkdir::WalkDir::new(source)
        .into_iter()
        .filter_map(|entry| entry.ok())
    {
        let relative = entry.path().strip_prefix(source).unwrap();
        let destination = target.join(relative);

        if entry.file_type().is_dir() {
            fs::create_dir_all(&destination)
                .with_context(|| format!("creating {}", destination.display()))?;
        } else if entry.file_type().is_file() {
            if let Some(parent) = destination.parent() {
                fs::create_dir_all(parent)
                    .with_context(|| format!("creating {}", parent.display()))?;
            }
            fs::copy(entry.path(), &destination).with_context(|| {
                format!(
                    "copying {} to {}",
                    entry.path().display(),
                    destination.display()
                )
            })?;
        }
    }

    Ok(())
}

fn display_command(command: &[String]) -> String {
    command
        .iter()
        .map(|arg| {
            if arg
                .chars()
                .any(|ch| ch.is_whitespace() || ch == '"' || ch == '\'')
            {
                format!("{arg:?}")
            } else {
                arg.clone()
            }
        })
        .collect::<Vec<_>>()
        .join(" ")
}

fn path_relative_string(root: &Path, path: &Path) -> Option<String> {
    path.strip_prefix(root).ok().map(normalize_relative)
}

fn normalize_relative(path: &Path) -> String {
    path.components()
        .filter_map(|component| match component {
            std::path::Component::Normal(value) => Some(value.to_string_lossy().to_string()),
            std::path::Component::CurDir => Some(".".to_string()),
            _ => None,
        })
        .collect::<Vec<_>>()
        .join("/")
}

fn absolutize_glob(base: &Path, pattern: &str) -> String {
    let candidate = Path::new(pattern);
    if candidate.is_absolute() {
        candidate.display().to_string()
    } else {
        base.join(candidate).display().to_string()
    }
}

fn slug(value: &str) -> String {
    let mut out = String::new();
    let mut last_dash = false;

    for ch in value.chars() {
        if ch.is_ascii_alphanumeric() {
            out.push(ch.to_ascii_lowercase());
            last_dash = false;
        } else if !last_dash {
            out.push('-');
            last_dash = true;
        }
    }

    out.trim_matches('-').to_string()
}

fn default_allow_patterns() -> Vec<String> {
    vec![
        "CI".to_string(),
        "GITHUB_*".to_string(),
        "RUSTUP_TOOLCHAIN".to_string(),
        "CARGO_*".to_string(),
    ]
}

fn default_deny_patterns() -> Vec<String> {
    vec![
        "*TOKEN*".to_string(),
        "*SECRET*".to_string(),
        "*PASSWORD*".to_string(),
        "AWS_*".to_string(),
        "GH_TOKEN".to_string(),
        "GITHUB_TOKEN".to_string(),
        "CARGO_REGISTRY_TOKEN".to_string(),
    ]
}

fn compile_patterns(patterns: &[String]) -> Vec<Pattern> {
    patterns
        .iter()
        .filter_map(|pattern| Pattern::new(pattern).ok())
        .collect()
}

fn matches_any(patterns: &[Pattern], value: &str) -> bool {
    patterns.iter().any(|pattern| pattern.matches(value))
}

fn probe_version(tool: &str) -> Option<String> {
    Command::new(tool)
        .arg("--version")
        .output()
        .ok()
        .filter(|output| output.status.success())
        .map(|output| {
            let stdout = String::from_utf8_lossy(&output.stdout).trim().to_string();
            if stdout.is_empty() {
                String::from_utf8_lossy(&output.stderr).trim().to_string()
            } else {
                stdout
            }
        })
        .filter(|value| !value.is_empty())
}

enum CommandOutcome {
    Completed(std::process::Output),
    SpawnError(std::io::Error),
}

fn run_command(cwd: &Path, command: &[String]) -> CommandOutcome {
    let mut cmd = Command::new(&command[0]);
    cmd.args(&command[1..]).current_dir(cwd);

    match cmd.output() {
        Ok(output) => CommandOutcome::Completed(output),
        Err(error) => CommandOutcome::SpawnError(error),
    }
}

#[cfg(unix)]
fn split_status(status: &std::process::ExitStatus) -> (Option<i32>, Option<i32>) {
    use std::os::unix::process::ExitStatusExt;

    (status.code(), status.signal())
}

#[cfg(not(unix))]
fn split_status(status: &std::process::ExitStatus) -> (Option<i32>, Option<i32>) {
    (status.code(), None)
}
